library(knitr)
library(scatterplot3d)
library(Rtsne)
library(coRanking)
library(dimRed)

setwd("/home/alexk101/Documents/Research_2020/tests/All_2D_Test_Output/")

mnistTSNE = embed(read.table("mnist_2D_TSNE.txt"))
mnistUMAP = embed(read.table("mnist_2D_UMAP.txt"))
mnistTrimap = embed(read.table("mnist_2D_Trimap.txt"))
mnistLargeVis = embed(read.table("mnist_2D_LargeVis.txt"))

fashionTSNE = embed(read.table("fashion_mnist_2D_TSNE.txt"))
fashionUMAP = embed(read.table("fashion_mnist_2D_UMAP.txt"))
fashionTrimap = embed(read.table("fashion_mnist_2D_Trimap.txt"))
fashionLargeVis = embed(read.table("fashion_mnist_2D_LargeVis.txt"))

coTSNEl = Q_local(mnistTSNE)
coUMAPl = Q_local(mnistUMAP)
coTrimapl = Q_local(mnistTrimap)
coLargeVisl = Q_local(mnistLargeVis)

coTSNEg = Q_global(mnistTSNE)
coUMAPg = Q_global(mnistUMAP)
coTrimapg = Q_global(mnistTrimap)
coLargeVisg = Q_global(mnistLargeVis)

coTSNEl_2 = Q_local(fashionTSNE)
coUMAPl_2 = Q_local(fashionUMAP)
coTrimapl_2 = Q_local(fashionTrimap)
coLargeVisl_2 = Q_local(fashionLargeVis)

coTSNEg_2 = Q_global(fashionTSNE)
coUMAPg_2 = Q_global(fashionUMAP)
coTrimapg_2 = Q_global(fashionTrimap)
coLargeVisg_2 = Q_global(fashionLargeVis)

file.create("output.txt")
write("coTSNEl: ",coTSNEl, "\n", file="output.txt")
write("coUMAPl: ",coUMAPl, "\n", file="output.txt")
write("coTrimapl: ",coTrimapl, "\n", file="output.txt")
write("coLargeVisl: ",coLargeVisl, "\n", file="output.txt")
write("coTSNEg: ",coTSNEg, "\n", file="output.txt")
write("coUMAPg: ",coUMAPg, "\n", file="output.txt")
write("coTrimapg: ",coTrimapg, "\n", file="output.txt")
write("coLargeVisg: ",coLargeVisg, "\n", file="output.txt")
write("coTSNEl_2: ",coTSNEl_2, "\n", file="output.txt")
write("coUMAPl_2: ",coUMAPl_2, "\n", file="output.txt")
write("coTrimapl_2: ",coTrimapl_2, "\n", file="output.txt")
write("coLargeVisl_2: ",coLargeVisl_2, "\n", file="output.txt")
write("coTSNEg_2: ",coTSNEg_2, "\n", file="output.txt")
write("coTSNEl: ",coTSNEl, "\n", file="output.txt")
write("coUMAPg_2: ",coUMAPg_2, "\n", file="output.txt")
write("coTrimapg_2: ",coTrimapg_2, "\n", file="output.txt")
write("coLargeVisg_2: ",coLargeVisg_2, "\n", file="output.txt")
